//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region Metadatos de relaciones en EDM

[assembly: EdmRelationshipAttribute("CarwashModel", "FK_Persona_Empleado", "Persona", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Carwash.Models.Persona), "Empleado", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Carwash.Models.Empleado), true)]

#endregion

namespace Carwash.Models
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class CarwashEntities : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto CarwashEntities usando la cadena de conexión encontrada en la sección 'CarwashEntities' del archivo de configuración de la aplicación.
        /// </summary>
        public CarwashEntities() : base("name=CarwashEntities", "CarwashEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto CarwashEntities.
        /// </summary>
        public CarwashEntities(string connectionString) : base(connectionString, "CarwashEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto CarwashEntities.
        /// </summary>
        public CarwashEntities(EntityConnection connection) : base(connection, "CarwashEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Empleado> Empleado
        {
            get
            {
                if ((_Empleado == null))
                {
                    _Empleado = base.CreateObjectSet<Empleado>("Empleado");
                }
                return _Empleado;
            }
        }
        private ObjectSet<Empleado> _Empleado;
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<Persona> Persona
        {
            get
            {
                if ((_Persona == null))
                {
                    _Persona = base.CreateObjectSet<Persona>("Persona");
                }
                return _Persona;
            }
        }
        private ObjectSet<Persona> _Persona;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Empleado. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToEmpleado(Empleado empleado)
        {
            base.AddObject("Empleado", empleado);
        }
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet Persona. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddToPersona(Persona persona)
        {
            base.AddObject("Persona", persona);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CarwashModel", Name="Empleado")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Empleado : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Empleado.
        /// </summary>
        /// <param name="empleado_id">Valor inicial de la propiedad Empleado_id.</param>
        /// <param name="persona_id">Valor inicial de la propiedad Persona_id.</param>
        public static Empleado CreateEmpleado(global::System.Int32 empleado_id, global::System.Int32 persona_id)
        {
            Empleado empleado = new Empleado();
            empleado.Empleado_id = empleado_id;
            empleado.Persona_id = persona_id;
            return empleado;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Empleado_id
        {
            get
            {
                return _Empleado_id;
            }
            set
            {
                if (_Empleado_id != value)
                {
                    OnEmpleado_idChanging(value);
                    ReportPropertyChanging("Empleado_id");
                    _Empleado_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Empleado_id");
                    OnEmpleado_idChanged();
                }
            }
        }
        private global::System.Int32 _Empleado_id;
        partial void OnEmpleado_idChanging(global::System.Int32 value);
        partial void OnEmpleado_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Persona_id
        {
            get
            {
                return _Persona_id;
            }
            set
            {
                OnPersona_idChanging(value);
                ReportPropertyChanging("Persona_id");
                _Persona_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Persona_id");
                OnPersona_idChanged();
            }
        }
        private global::System.Int32 _Persona_id;
        partial void OnPersona_idChanging(global::System.Int32 value);
        partial void OnPersona_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Salario_id
        {
            get
            {
                return _Salario_id;
            }
            set
            {
                OnSalario_idChanging(value);
                ReportPropertyChanging("Salario_id");
                _Salario_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Salario_id");
                OnSalario_idChanged();
            }
        }
        private Nullable<global::System.Int32> _Salario_id;
        partial void OnSalario_idChanging(Nullable<global::System.Int32> value);
        partial void OnSalario_idChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CarwashModel", "FK_Persona_Empleado", "Persona")]
        public Persona Persona
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("CarwashModel.FK_Persona_Empleado", "Persona").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("CarwashModel.FK_Persona_Empleado", "Persona").Value = value;
            }
        }
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Persona> PersonaReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Persona>("CarwashModel.FK_Persona_Empleado", "Persona");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Persona>("CarwashModel.FK_Persona_Empleado", "Persona", value);
                }
            }
        }

        #endregion

    }
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="CarwashModel", Name="Persona")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Persona : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto Persona.
        /// </summary>
        /// <param name="persona_id">Valor inicial de la propiedad Persona_id.</param>
        /// <param name="tipoDocumento">Valor inicial de la propiedad TipoDocumento.</param>
        /// <param name="identificacion">Valor inicial de la propiedad Identificacion.</param>
        /// <param name="nombre">Valor inicial de la propiedad Nombre.</param>
        public static Persona CreatePersona(global::System.Int32 persona_id, global::System.String tipoDocumento, global::System.String identificacion, global::System.String nombre)
        {
            Persona persona = new Persona();
            persona.Persona_id = persona_id;
            persona.TipoDocumento = tipoDocumento;
            persona.Identificacion = identificacion;
            persona.Nombre = nombre;
            return persona;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 Persona_id
        {
            get
            {
                return _Persona_id;
            }
            set
            {
                if (_Persona_id != value)
                {
                    OnPersona_idChanging(value);
                    ReportPropertyChanging("Persona_id");
                    _Persona_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Persona_id");
                    OnPersona_idChanged();
                }
            }
        }
        private global::System.Int32 _Persona_id;
        partial void OnPersona_idChanging(global::System.Int32 value);
        partial void OnPersona_idChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String TipoDocumento
        {
            get
            {
                return _TipoDocumento;
            }
            set
            {
                OnTipoDocumentoChanging(value);
                ReportPropertyChanging("TipoDocumento");
                _TipoDocumento = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("TipoDocumento");
                OnTipoDocumentoChanged();
            }
        }
        private global::System.String _TipoDocumento;
        partial void OnTipoDocumentoChanging(global::System.String value);
        partial void OnTipoDocumentoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Identificacion
        {
            get
            {
                return _Identificacion;
            }
            set
            {
                OnIdentificacionChanging(value);
                ReportPropertyChanging("Identificacion");
                _Identificacion = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Identificacion");
                OnIdentificacionChanged();
            }
        }
        private global::System.String _Identificacion;
        partial void OnIdentificacionChanging(global::System.String value);
        partial void OnIdentificacionChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Nombre
        {
            get
            {
                return _Nombre;
            }
            set
            {
                OnNombreChanging(value);
                ReportPropertyChanging("Nombre");
                _Nombre = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Nombre");
                OnNombreChanged();
            }
        }
        private global::System.String _Nombre;
        partial void OnNombreChanging(global::System.String value);
        partial void OnNombreChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Apellido
        {
            get
            {
                return _Apellido;
            }
            set
            {
                OnApellidoChanging(value);
                ReportPropertyChanging("Apellido");
                _Apellido = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Apellido");
                OnApellidoChanged();
            }
        }
        private global::System.String _Apellido;
        partial void OnApellidoChanging(global::System.String value);
        partial void OnApellidoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Correo
        {
            get
            {
                return _Correo;
            }
            set
            {
                OnCorreoChanging(value);
                ReportPropertyChanging("Correo");
                _Correo = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Correo");
                OnCorreoChanged();
            }
        }
        private global::System.String _Correo;
        partial void OnCorreoChanging(global::System.String value);
        partial void OnCorreoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefono
        {
            get
            {
                return _Telefono;
            }
            set
            {
                OnTelefonoChanging(value);
                ReportPropertyChanging("Telefono");
                _Telefono = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefono");
                OnTelefonoChanged();
            }
        }
        private global::System.String _Telefono;
        partial void OnTelefonoChanging(global::System.String value);
        partial void OnTelefonoChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Direccion
        {
            get
            {
                return _Direccion;
            }
            set
            {
                OnDireccionChanging(value);
                ReportPropertyChanging("Direccion");
                _Direccion = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Direccion");
                OnDireccionChanged();
            }
        }
        private global::System.String _Direccion;
        partial void OnDireccionChanging(global::System.String value);
        partial void OnDireccionChanged();

        #endregion

    
        #region Propiedades de navegación
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("CarwashModel", "FK_Persona_Empleado", "Empleado")]
        public EntityCollection<Empleado> Empleado
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Empleado>("CarwashModel.FK_Persona_Empleado", "Empleado");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Empleado>("CarwashModel.FK_Persona_Empleado", "Empleado", value);
                }
            }
        }

        #endregion

    }

    #endregion

    
}
